import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import type { RootState, AppThunk } from "src/store"

interface bottomNavigationState {
  value: number
}

const initialState: bottomNavigationState = {
  value: 1
}
const bottomNavigationSlice = createSlice({
  name: 'bottomNavigation',
  initialState,
  reducers: {
    changeBottomNavigation: (state, action: PayloadAction<number>) => {
      state.value = action.payload
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: () => {},
})
const selectBottomNavigation = (state: RootState) => state.bottomNavigation.value
const { changeBottomNavigation } = bottomNavigationSlice.actions
const bottomNavigationReducer = bottomNavigationSlice.reducer

export { bottomNavigationSlice, selectBottomNavigation, changeBottomNavigation, bottomNavigationReducer }