import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import type { RootState, AppThunk } from "src/store"

interface bottomNavigationState {
  value: number
}

const getInitialValue = (): number => {
  if (typeof window !== 'undefined') {
    const pathname = window.location.pathname
    if (pathname === '/add') {
      return 0
    } else if (pathname === '/') {
      return 1
    } else if (pathname === '/board') {
      return 2
    } else {
      return 5
    }
  }
  return 1 // fallback for server-side rendering
}

const initialState: bottomNavigationState = {
  value: getInitialValue()
}

const bottomNavigationSlice = createSlice({
  name: 'bottomNavigation',
  initialState,
  reducers: {
    changeBottomNavigation: (state, action: PayloadAction<number>) => {
      state.value = action.payload
    },
  },
  selectors: {
    selectBottomNavigations: (state) => state.value
  }
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: () => {},
})
// const selectBottomNavigation = (state: RootState) => state.bottomNavigation.value
const { changeBottomNavigation } = bottomNavigationSlice.actions
const bottomNavigationReducer = bottomNavigationSlice.reducer

export { bottomNavigationSlice, changeBottomNavigation, bottomNavigationReducer }