import { createSlice, PayloadAction } from '@reduxjs/toolkit'

interface scrollNavigationState {
  value: boolean
}

const initialState: scrollNavigationState = {
  value: false
}
const scrollNavigationSlice = createSlice({
  name: 'scrollNavigation',
  initialState,
  reducers: {
    changeScrollNavigation: (state, action: PayloadAction<boolean>) => {
      state.value = action.payload
    },
  },
  selectors: {
    selectScrollNavigation: (state) => state.value
  }
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: () => {},
})
// const selectBottomNavigation = (state: RootState) => state.bottomNavigation.value
const { changeScrollNavigation } = scrollNavigationSlice.actions
const scrollNavigationReducer = scrollNavigationSlice.reducer

export { changeScrollNavigation, scrollNavigationReducer, scrollNavigationSlice }

