import { createSlice, PayloadAction } from '@reduxjs/toolkit'

interface userCertificatedState {
  value: boolean
}

const initialState: userCertificatedState = {
  value: false
}
const userCertificatedSlice = createSlice({
  name: 'userCertificated',
  initialState,
  reducers: {
    changeUserCertificated: (state, action: PayloadAction<boolean>) => {
      state.value = action.payload
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: () => {},
})
// const selectBottomNavigation = (state: RootState) => state.bottomNavigation.value
const { changeUserCertificated } = userCertificatedSlice.actions
const userCertificatedReducer = userCertificatedSlice.reducer

export { changeUserCertificated, userCertificatedReducer, userCertificatedSlice }

