export const sebeopKo = [
  "B101\t후마니타스 교재집필실",
  "B102\t비폭력연구소1",
  "B103\t후마니타스 교재집필실",
  "B104\t비폭력연구소2",
  "102\tK컬쳐ㆍ스토리콘텐츠 연구소",
  "103\tK컬쳐ㆍ스토리콘텐츠 연구소",
  "104\tK컬쳐ㆍ스토리콘텐츠 연구소",
  "201\t비폭력연구소",
  "204\tK컬쳐ㆍ스토리콘텐츠 연구소",
  "301\t미래사회에너지정책연구원",
  "302\t미래사회에너지정책연구원",
  "303\t미래사회에너지정책연구원",
];
export const sebeopEn = [
  "B101\tHumanitas Textbook Writing Room",
  "B102\tInstitute for Nonviolence 1",
  "B103\tHumanitas Textbook Writing Room",
  "B104\tInstitute for Nonviolence 2",
  "102\tK-Culture & Story Content Research Institute",
  "103\tK-Culture & Story Content Research Institute",
  "104\tK-Culture & Story Content Research Institute",
  "201\tInstitute for Nonviolence",
  "204\tK-Culture & Story Content Research Institute",
  "301\tFuture Society Energy Policy Research Institute",
  "302\tFuture Society Energy Policy Research Institute",
  "303\tFuture Society Energy Policy Research Institute",
];
