export const semKo = [
  "101	학생회실	미술대학관",
  "102	조소실기실	미술대학관",
  "103	조소실기실	미술대학관",
  "104	조소실기실	미술대학관",
  "105	조소실기실	미술대학관",
  "108	유류고	미술대학관",
  "000	분리수거장	경희미술관",
  "101	제1전시실	경희미술관",
  "200	조소실기실	미술대학관",
  "201	현대미술연구소	미술대학관",
  "202	미술대학학장실	미술대학관",
  "203	미술대학행정실	미술대학관",
  "205	기자재보관실	미술대학관",
  "206	메이커스페이스	미술대학관",
  "208	미디어랩	미술대학관",
  "209	209 강의실	미술대학관",
  "210	사진실	미술대학관",
  "201	제2전시실	경희미술관",
  "300	조소실기실	미술대학관",
  "301-1	교강사휴게실	미술대학관",
  "308	대학원실기실	미술대학관",
  "309	대학원실기실	미술대학관",
  "310	대학원실	미술대학관",
  "301	제3전시실	경희미술관",
  "400	한국화실기실	미술대학관",
  "401	회화실기실	미술대학관",
  "402	회화실기실	미술대학관",
  "403	회화실기실	미술대학관",
  "404	회화실기실	미술대학관",
  "405	회화실기실	미술대학관",
  "406	회화실기실	미술대학관",
  "401	제4전시실	경희미술관",
  "500	한국화실기실	미술대학관",
  "501	한국화실기실	미술대학관",
  "502	회화실기실	미술대학관",
  "503	회화실기실	미술대학관",
  "504	강의실	미술대학관",
  "505	판화실	미술대학관",
  "501	강의실	경희미술관",
  "600	한국화실기실	미술대학관",
  "601	한국화실기실	미술대학관",
  "602	한국화실기실	미술대학관",
  "603	회화실기실	미술대학관",
  "604	회화실기실	미술대학관",
  "605-1	회화실기실	미술대학관",
  "605-2	회화실기실	미술대학관",
  "606	매점	미술대학관",
  "700	대학원실기실	미술대학관",
  "701	대학원실기실	미술대학관",
  "702	물탱크실		미술대학관",
];
export const semEn = [
  "101	Student Council Room	College of Fine Arts Building",
  "102	Sculpture Practice Room	College of Fine Arts Building",
  "103	Sculpture Practice Room	College of Fine Arts Building",
  "104	Sculpture Practice Room	College of Fine Arts Building",
  "105	Sculpture Practice Room	College of Fine Arts Building",
  "108	Oil Storage	College of Fine Arts Building",
  "000	Recycling Station	Kyung Hee Museum of Art",
  "101	Exhibition Hall 1	Kyung Hee Museum of Art",
  "200	Sculpture Practice Room	College of Fine Arts Building",
  "201	Institute of Contemporary Art	College of Fine Arts Building",
  "202	Dean’s Office, College of Fine Arts	College of Fine Arts Building",
  "203	Administration Office, College of Fine Arts	College of Fine Arts Building",
  "205	Equipment Storage Room	College of Fine Arts Building",
  "206	Makerspace	College of Fine Arts Building",
  "208	Media Lab	College of Fine Arts Building",
  "209	Lecture Room 209	College of Fine Arts Building",
  "210	Photography Room	College of Fine Arts Building",
  "201	Exhibition Hall 2	Kyung Hee Museum of Art",
  "300	Sculpture Practice Room	College of Fine Arts Building",
  "301-1	Faculty Lounge	College of Fine Arts Building",
  "308	Graduate Practice Room	College of Fine Arts Building",
  "309	Graduate Practice Room	College of Fine Arts Building",
  "310	Graduate Room	College of Fine Arts Building",
  "301	Exhibition Hall 3	Kyung Hee Museum of Art",
  "400	Korean Painting Practice Room	College of Fine Arts Building",
  "401	Painting Practice Room	College of Fine Arts Building",
  "402	Painting Practice Room	College of Fine Arts Building",
  "403	Painting Practice Room	College of Fine Arts Building",
  "404	Painting Practice Room	College of Fine Arts Building",
  "405	Painting Practice Room	College of Fine Arts Building",
  "406	Painting Practice Room	College of Fine Arts Building",
  "401	Exhibition Hall 4	Kyung Hee Museum of Art",
  "500	Korean Painting Practice Room	College of Fine Arts Building",
  "501	Korean Painting Practice Room	College of Fine Arts Building",
  "502	Painting Practice Room	College of Fine Arts Building",
  "503	Painting Practice Room	College of Fine Arts Building",
  "504	Lecture Room	College of Fine Arts Building",
  "505	Printmaking Room	College of Fine Arts Building",
  "501	Lecture Room	Kyung Hee Museum of Art",
  "600	Korean Painting Practice Room	College of Fine Arts Building",
  "601	Korean Painting Practice Room	College of Fine Arts Building",
  "602	Korean Painting Practice Room	College of Fine Arts Building",
  "603	Painting Practice Room	College of Fine Arts Building",
  "604	Painting Practice Room	College of Fine Arts Building",
  "605-1	Painting Practice Room	College of Fine Arts Building",
  "605-2	Painting Practice Room	College of Fine Arts Building",
  "606	Snack Bar	College of Fine Arts Building",
  "700	Graduate Practice Room	College of Fine Arts Building",
  "701	Graduate Practice Room	College of Fine Arts Building",
  "702	Water Tank Room		College of Fine Arts Building",
];
